# Generated by Django 3.0.4 on 2020-04-05 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Must be valid...', regex='^[A-Za-z]{3,50}$')]),
        ),
    ]
