# Generated by Django 3.0.4 on 2020-04-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
