# Generated by Django 3.0.4 on 2020-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=50, verbose_name='Delivery Address'),
        ),
    ]
