# Generated by Django 3.0.4 on 2020-03-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200326_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
